import datetime
MILLIMETER = MILLIMETERS = 1
METER = METERS = 1000 * MILLIMETERS
KILOMETER = KILOMETERS = 1000 * METERS

SECOND = SECONDS = 1
MINUTE = MINUTES = 60 * SECONDS  # note: this is wrong in case of leapseconds
HOUR = HOURS = 60 * MINUTES
DAY = DAYS = 24 * HOURS  # note: this is wrong on days that DST starts/ends
WEEK = WEEKS = 7 * DAYS

SECOND_TD = SECONDS_TD = datetime.timedelta(seconds=1)
MINUTE_TD = MINUTES_TD = MINUTE * SECONDS_TD
HOUR_TD = HOURS_TD = HOUR * SECONDS_TD
DAY_TD = DAYS_TD = DAY * SECONDS_TD
WEEK_TD = WEEKS_TD = WEEK * SECONDS_TD
